version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8080:80
    networks:
      - app-network

  mysql:
    image: mysql:8.0.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 127.0.0.1:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: course_selection
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
